apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-k8s
  template:
    metadata:
      labels:
        app: microservice-k8s
    spec:
      containers:
      - name: microservice-k8s
        image: microservice-k8s:latest
        ports:
        - containerPort: 8000
