apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskserver
        image: ikramkhan1/mlops_ct2:v1
        ports:
        - containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 31110
